### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by tansatrisna** [anoerman/invenitri#1]
Halo anoerman,
terima kasih telah berbagi projek sistem informasi inventaris ini.
Namun pada saat saya instalasi projek, dan mencoba untuk menambahkan user menemukan error yaitu:

Error Number: 1146

Table 'arc_database.users_photo' doesn't exist

Mohon bantuannya, apakah ada yang saya lewatkan dalam menginstal projek ini?
Terima kasih

**Comment by msazzuhair** [comment]
Sepertinya masalahnya ada pada trigger di file ```invenitri_database.sql``` karena menggunakan nama tabel 'arc_database.users_photo' (dengan tambahan reference nama schema 'arc_database')

**Comment by anoerman** [comment]
Terima kasih mas @msazzuhair sudah di infokan salahnya dimana, file sql sudah di update sesuai dengan yang mas sampaikan.
